set_property PACKAGE_PIN R1 [get_ports {Flags[3]}]
set_property PACKAGE_PIN P2 [get_ports {Flags[2]}]
set_property PACKAGE_PIN P1 [get_ports {Flags[1]}]
set_property PACKAGE_PIN N2 [get_ports {Flags[0]}]
set_property PACKAGE_PIN U3 [get_ports {in[1]}]
set_property PACKAGE_PIN T3 [get_ports {in[0]}]
set_property PULLDOWN true [get_ports {in[0]}]
set_property PULLDOWN true [get_ports {in[1]}]
set_property PULLDOWN true [get_ports {OP[0]}]
set_property PULLDOWN true [get_ports {OP[1]}]
set_property PULLDOWN true [get_ports {OP[2]}]
set_property PULLDOWN true [get_ports {OP[3]}]
set_property PACKAGE_PIN T4 [get_ports {OP[0]}]
set_property PACKAGE_PIN V3 [get_ports {OP[1]}]
set_property PACKAGE_PIN V4 [get_ports {OP[2]}]
set_property PACKAGE_PIN W4 [get_ports {OP[3]}]
set_property PACKAGE_PIN H19 [get_ports {seg[7]}]
set_property PACKAGE_PIN G20 [get_ports {seg[6]}]
set_property PACKAGE_PIN J22 [get_ports {seg[5]}]
set_property PACKAGE_PIN K22 [get_ports {seg[4]}]
set_property PACKAGE_PIN K21 [get_ports {seg[3]}]
set_property PACKAGE_PIN H20 [get_ports {seg[2]}]
set_property PACKAGE_PIN H22 [get_ports {seg[1]}]
set_property PACKAGE_PIN J21 [get_ports {seg[0]}]
set_property PACKAGE_PIN M22 [get_ports {which[2]}]
set_property PACKAGE_PIN M21 [get_ports {which[1]}]
set_property PACKAGE_PIN N22 [get_ports {which[0]}]
set_property PULLDOWN true [get_ports rst_n]
set_property PACKAGE_PIN AB7 [get_ports rst_n]
set_property PACKAGE_PIN R4 [get_ports clk_A]
set_property PACKAGE_PIN AA4 [get_ports clk_B]
set_property PACKAGE_PIN AB6 [get_ports clk_F]
set_property PULLDOWN true [get_ports clk_F]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property PULLDOWN true [get_ports clk_A]
set_property PULLDOWN true [get_ports clk_B]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_B]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_A]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_F]



set_property PACKAGE_PIN L21 [get_ports enable]
set_property PACKAGE_PIN H4 [get_ports clk]
